name: kindling
channels:
- pytorch
- defaults
dependencies:
- appnope=0.1.2
- argon2-cffi=21.3.0
- argon2-cffi-bindings=21.2.0
- asttokens=2.0.5
- attrs=21.4.0
- backcall=0.2.0
- blas=1.0
- bleach=4.1.0
- brotlipy=0.7.0
- bzip2=1.0.8
- ca-certificates=2022.3.18
- certifi=2021.10.8
- cffi=1.15.0
- charset-normalizer=2.0.4
- cryptography=36.0.0
- dbus=1.13.18
- debugpy=1.5.1
- decorator=5.1.1
- defusedxml=0.7.1
- entrypoints=0.3
- executing=0.8.3
- expat=2.4.4
- ffmpeg=4.3
- freetype=2.11.0
- gettext=0.21.0
- giflib=5.2.1
- glib=2.69.1
- gmp=6.2.1
- gnutls=3.6.15
- icu=58.2
- idna=3.3
- importlib-metadata=4.8.2
- importlib_metadata=4.8.2
- intel-openmp=2021.4.0
- ipykernel=6.9.1
- ipython=8.1.1
- ipython_genutils=0.2.0
- ipywidgets=7.6.5
- jedi=0.18.1
- jinja2=3.0.3
- jpeg=9d
- jsonschema=3.2.0
- jupyter=1.0.0
- jupyter_client=7.1.2
- jupyter_console=6.4.3
- jupyter_core=4.9.2
- jupyterlab_pygments=0.1.2
- jupyterlab_widgets=1.0.0
- lame=3.100
- lcms2=2.12
- libcxx=12.0.0
- libffi=3.3
- libiconv=1.16
- libidn2=2.3.2
- libpng=1.6.37
- libsodium=1.0.18
- libtasn1=4.16.0
- libtiff=4.2.0
- libunistring=0.9.10
- libuv=1.40.0
- libwebp=1.2.2
- libwebp-base=1.2.2
- libxml2=2.9.12
- llvm-openmp=12.0.0
- lz4-c=1.9.3
- markupsafe=2.0.1
- matplotlib-inline=0.1.2
- mistune=0.8.4
- mkl=2021.4.0
- mkl-service=2.4.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- nbclient=0.5.11
- nbconvert=6.3.0
- nbformat=5.1.3
- ncurses=6.3
- nest-asyncio=1.5.1
- nettle=3.7.3
- notebook=6.4.8
- numpy=1.21.2
- numpy-base=1.21.2
- openh264=2.1.1
- openssl=1.1.1n
- packaging=21.3
- pandocfilters=1.5.0
- parso=0.8.3
- pcre=8.45
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=9.0.1
- pip=21.2.4
- prometheus_client=0.13.1
- prompt-toolkit=3.0.20
- prompt_toolkit=3.0.20
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pycparser=2.21
- pygments=2.11.2
- pyopenssl=22.0.0
- pyparsing=3.0.4
- pyqt=5.9.2
- pyrsistent=0.18.0
- pysocks=1.7.1
- python=3.8.12
- python-dateutil=2.8.2
- pytorch=1.11.0
- pyzmq=22.3.0
- qt=5.9.7
- qtconsole=5.2.2
- qtpy=1.11.2
- readline=8.1.2
- requests=2.27.1
- send2trash=1.8.0
- setuptools=58.0.4
- sip=4.19.8
- six=1.16.0
- sqlite=3.37.2
- stack_data=0.2.0
- terminado=0.13.1
- testpath=0.5.0
- tk=8.6.11
- torchaudio=0.11.0
- torchvision=0.12.0
- tornado=6.1
- traitlets=5.1.1
- typing-extensions=4.1.1
- typing_extensions=4.1.1
- urllib3=1.26.8
- wcwidth=0.2.5
- webencodings=0.5.1
- wheel=0.37.1
- widgetsnbextension=3.5.2
- xz=5.2.5
- zeromq=4.3.4
- zipp=3.7.0
- zlib=1.2.11
- zstd=1.4.9
- pip:
  - antlr4-python3-runtime==4.8
  - black==22.1.0
  - cfgv==3.3.1
  - click==8.0.4
  - cycler==0.11.0
  - distlib==0.3.4
  - docker-pycreds==0.4.0
  - filelock==3.6.0
  - flake8==4.0.1
  - fonttools==4.31.2
  - gitdb==4.0.9
  - gitpython==3.1.27
  - hydra-core==1.1.1
  - identify==2.4.12
  - importlib-resources==5.4.0
  - isort==5.10.1
  - kiwisolver==1.4.0
  - matplotlib==3.5.1
  - mccabe==0.6.1
  - mypy-extensions==0.4.3
  - nodeenv==1.6.0
  - omegaconf==2.1.1
  - pathspec==0.9.0
  - pathtools==0.1.2
  - platformdirs==2.5.1
  - pre-commit==2.17.0
  - promise==2.3
  - protobuf==3.19.4
  - psutil==5.9.0
  - pycodestyle==2.8.0
  - pyflakes==2.4.0
  - pyyaml==6.0
  - sentry-sdk==1.5.8
  - setproctitle==1.2.2
  - shortuuid==1.0.8
  - smmap==5.0.0
  - termcolor==1.1.0
  - toml==0.10.2
  - tomli==2.0.1
  - virtualenv==20.13.4
  - wandb==0.12.11
  - yaspin==2.1.0
